# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

steps:
-   task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
      python.version: '3.10'
-   script: |
      python -m pip install -r TestCases/requirements.txt && webdrivermanager chrome --linkpath TestCases
    displayName: 'Setup Robot Framework'
-   task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
      
        Write-Host "Hello World"
        robot -x outputxunit.xml "TestCases"