# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
      python.version: '3.10'




- script: |
    python -m pip install -r requirements.txt
    && webdrivermanager chrome -- linkpath AUTO
  displayName: 'Install Robot Framework'

- script: |
    robot -x outputxunit.xml "TestCases"
  displayName: 'Run Robot Tests'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
